#!/bin/bash

# Add Swift Package Dependencies to BaseCrawler-Mac
# This script will guide you through adding database driver packages to your Xcode project

echo "=========================================="
echo "BaseCrawler-Mac Package Dependencies Setup"
echo "=========================================="
echo ""
echo "You need to add the following Swift Package dependencies to your Xcode project:"
echo ""
echo "1. PostgreSQL Driver (PostgresNIO)"
echo "   URL: https://github.com/vapor/postgres-nio.git"
echo "   Version: 1.21.0 or later"
echo ""
echo "2. MySQL Driver (MySQLNIO)"
echo "   URL: https://github.com/vapor/mysql-nio.git"
echo "   Version: 1.8.0 or later"
echo ""
echo "3. MongoDB Driver (MongoSwift)"
echo "   URL: https://github.com/mongodb/mongo-swift-driver.git"
echo "   Version: 1.3.1 or later"
echo ""
echo "4. Redis Driver (RediStack)"
echo "   URL: https://github.com/swift-server/RediStack.git"
echo "   Version: 1.6.0 or later"
echo ""
echo "=========================================="
echo "HOW TO ADD PACKAGES IN XCODE:"
echo "=========================================="
echo ""
echo "1. Open BaseCrawler-Mac.xcodeproj in Xcode"
echo "2. Select the project in the navigator (top-level 'BaseCrawler-Mac')"
echo "3. Select the 'BaseCrawler-Mac' target"
echo "4. Go to the 'General' tab"
echo "5. Scroll down to 'Frameworks, Libraries, and Embedded Content'"
echo "6. Click the '+' button below that section"
echo "7. Click 'Add Package Dependency...'"
echo "8. Paste one of the URLs above"
echo "9. Select the appropriate version"
echo "10. Click 'Add Package'"
echo "11. Select the package products to add (usually all of them)"
echo "12. Repeat for each package"
echo ""
echo "=========================================="
echo "OR USE THIS QUICK METHOD:"
echo "=========================================="
echo ""
echo "In Xcode, go to File > Add Package Dependencies..."
echo "Then add each URL above one by one."
echo ""
echo "Press any key to continue..."
read -n 1 -s

echo ""
echo "Opening Xcode project..."
open "/Users/christopher/Developer/Github/BaseCrawler-Mac/BaseCrawler-Mac.xcodeproj"
